config/routes.rb
OmgBlog::Application.routes.draw do
  devise_for :users
  resources :articles
  resources :comments, only: [:create]

  root to: 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :user_id, presence: true
  validates :title, presence: true
  validates :text, presence: true, length: { minimum: 30 }

  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    if params.has_key?(:tag)
      @articles = Article.find_by_sql("SELECT * FROM articles WHERE tags LIKE '%#{params[:tag]}%'")
      @tag = params[:tag]
    elsif params.has_key?(:author)
      @articles = Article.where(user_id: User.find_by(email: params[:author]))
      @author = params[:author]
    else
      @articles = Article.all
    end
  end

  def show
    begin
      @article = Article.find(params[:id])
      @comment = Comment.new
    rescue ActiveRecord::RecordNotFound => e
      flash[:notice] = 'No such article'
      redirect_to root_path
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(user_id: current_user.id, title: params[:article][:title], text: params[:article][:text], tags: params[:article][:tags])
    if @article.save
      redirect_to @article
    else
      flash.now[:notice] = @article.errors.full_messages.to_s
      render 'new'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    user_id = nil
    user_id = current_user.id if current_user
    @comment = Comment.new(user_id: user_id, article_id: params[:comment][:article_id], text: params[:comment][:text])
    @comment.save
    redirect_to Article.find(params[:comment][:article_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.haml
- if @tag
  filtered by tag:
  = link_to @tag, articles_path(tag: @tag)
  |
  = link_to 'remove filter', articles_path
%br
- if @author
  filtered by author:
  = link_to @author, articles_path(author: @author)
  |
  = link_to 'remove filter', articles_path
%br
%br
- @articles.each do |article|
  %p
    = link_to article.title, article_path(article)

app/views/articles/new.html.haml
= form_for @article do |f|
  = f.text_field :title, size: 50
  %br
  = f.text_field :tags, size: 50, placeholder: "list of tags delimited with whitespaces"
  %br
  = f.text_area :text, size: "100x20"
  %br
  = f.submit "Publish article!"

app/views/articles/show.html.haml
%strong
  %font{ size: '6' }= @article.title
%br
%strong author: 
= link_to @article.user.email, articles_path(author: @article.user.email)
%br
%strong posted at:
= @article.created_at
%br
%strong tags: 
- @article.tags.split(" ").each do |tag|
  = link_to tag, articles_path(tag: tag)
%br
%br
= simple_format @article.text

.new_comment
  =render 'comments/new'

.comments
  =render 'comments/index'
  

app/views/comments/_index.html.haml
- @article.comments.each do |comment|
  .comment
    - if comment.user
      = link_to comment.user.email, articles_path(author: comment.user.email)
    - else
      %strong Anonimous
    comment:
    %br
    = comment.text

app/views/comments/_new.html.haml
= form_for @comment do |f|
  = f.hidden_field :article_id, value: @article.id
  = f.text_area :text, size: "100x2"
  = f.submit 'post comment'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
      - if user_signed_in?
        .navbar-brand= current_user.email
        = link_to 'Sign out', destroy_user_session_path, class: 'navbar-brand', method: :delete
        = link_to 'Write article', new_article_path, class: 'navbar-brand'
        /TODO: show user links: create article, edit acc, etc...
      -else
        = link_to 'Sign in', new_user_session_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Omg Blog"
    %meta{:content => content_for?(:description) ? yield(:description) : "Omg Blog", :name => "description"}/
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield